apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-access
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
  - from:
    - ipBlock:
        cidr: {IP_ADDRESS}/32
